# name: CI
# on: [push, pull_request]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-java@v4
#         with:
#           distribution: temurin
#           java-version: 17
#           cache: maven
#       - run: ./mvnw -B -DskipTests=false verify
#       - run: ./mvnw -B -DskipTests package
#       - uses: actions/upload-artifact@v4
#         with:
#           name: app-jar
#           path: target/*.jar

name: CI
on:
  push:
    branches: ["*", "!main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:


    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml -Dmaven.test.skip
